# Generated by Django 5.1.7 on 2025-05-09 10:36

import django.contrib.auth.models
import django.db.models.deletion
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRegisterView",
            fields=[
                (
                    "permission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.permission",
                    ),
                ),
            ],
            bases=(django.views.generic.edit.CreateView, "auth.permission"),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
