# Generated by Django 5.1.7 on 2025-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": [
                    "title",
                    "is_published",
                    "created_at",
                    "updated_at",
                    "views_count",
                ],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="views",
            new_name="views_count",
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/blogs",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Заголовок"),
        ),
    ]
