# Generated by Django 5.1.7 on 2025-04-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_options_rename_views_blog_views_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счетчик просмотров"
            ),
        ),
    ]
